'use client';
import { useI18n } from '@/lib/i18n';

// Shared design tokens, formatters and bilingual labels for the whole online-orders section
// (Order/Track/Stats/Customers tabs). Split out of OnlineOrdersView.tsx (2026-09-11) so
// CustomersTab.tsx can import them without a circular import between the two client components.

export const NAVY = '#1A4731';
export const GOLD = '#C9A84C';
export const CREAM = '#FFF4CC';
export const CREAM_DARK = '#F5E89A';
export const INK = '#1A2C24';
export const INK_LIGHT = '#6B7280';
export const BORDER = '#E0D49A';
export const TABBAR = '#163D29';

export function fmtVnd(v: number): string {
  return `${Math.round(v).toLocaleString('vi-VN')} ₫`;
}
export function fmtDayLabel(key: string, lang: 'vi' | 'en'): string {
  // key is 'YYYY-MM-DD'; build the Date via local components to avoid UTC off-by-one.
  const [y, m, d] = key.split('-').map(Number);
  const dt = new Date(y, (m || 1) - 1, d || 1);
  return dt.toLocaleDateString(lang === 'en' ? 'en-GB' : 'vi-VN', { weekday: 'short', day: '2-digit', month: '2-digit' });
}
export function fmtCompactVnd(v: number): string {
  if (v >= 1_000_000) return `${(v / 1_000_000).toFixed(1)}M ₫`;
  if (v >= 1_000) return `${Math.round(v / 1_000)}k ₫`;
  return `${Math.round(v)} ₫`;
}

// ── Bilingual labels (Axel, 2026-09-06: "met son interface anglais viet aussi") — same
// localStorage-backed toggle as the rest of the app (useI18n), default VI for her, EN for Axel.
export const L = {
  vi: {
    titleOrder: 'Đơn hàng Online',
    titleTrack: 'Theo dõi đơn hàng',
    titleStats: 'Thống kê doanh thu',
    tabOrder: 'Đặt hàng',
    tabTrack: 'Theo dõi',
    tabStats: 'Thống kê',
    items: 'SP',
    bell: 'Thông báo',
    logout: 'Đăng xuất',
    logoutConfirm: 'Đăng xuất khỏi tài khoản này?',
    channelLabel: 'Kênh bán hàng',
    channelHint: 'Nguồn khách hàng — dùng để thống kê, không quyết định shop xử lý đơn.',
    shopLabel: 'Shop xử lý đơn (tạo trên Odoo)',
    deliveryModeLabel: 'Ai giao cho khách',
    dmShop: '🏪 Giao qua shop',
    dmDirect: '🚚 Lab giao thẳng',
    dmShopHint: 'Lab giao hàng đến shop, shop giao/khách nhận tại shop (như hiện tại).',
    dmDirectHint: 'Lab tự giao thẳng đến địa chỉ khách, không qua shop.',
    addProduct: 'Thêm sản phẩm',
    searchPh: 'Tìm sản phẩm theo tên...',
    unitPrice: 'Đơn giá (₫)',
    cakeMsg: 'Lời nhắn trên bánh (ví dụ: Happy Birthday Linh)',
    designNotes: 'Ghi chú thiết kế bánh...',
    designPhoto: 'Ảnh thiết kế khác',
    designPhotoHint: 'Mẫu gốc ở trên. Chỉ thêm ảnh tham khảo nếu khách muốn thiết kế KHÁC mẫu gốc.',
    customerInfo: 'Thông tin khách hàng',
    custName: 'Tên khách hàng',
    custPhone: 'Số điện thoại',
    address: 'Địa chỉ giao hàng',
    extraNotes: 'Ghi chú thêm...',
    payment: 'Thanh toán',
    deliveryFee: 'Phí giao hàng',
    total: 'Tổng cộng',
    paid: '✓ Đã TT',
    unpaid: 'Chưa TT',
    partial: 'Cọc 1 phần',
    depositAmount: 'Số tiền đã cọc (₫)',
    creating: 'Đang tạo đơn...',
    submit: 'Tạo đơn & gửi Odoo',
    errChannel: 'Chọn hoặc nhập kênh bán hàng',
    errEmpty: 'Giỏ hàng trống',
    okOdoo: 'Đã tạo đơn Odoo: ',
    okSaved: 'Đã lưu đơn hàng',
    fAll: 'Tất cả',
    fUndelivered: 'Chưa giao',
    fLate: '⚠ Trễ hạn',
    noOrders: 'Chưa có đơn hàng nào.',
    deliveryDateGroup: 'Giao ngày',
    noDeliveryDate: 'Chưa có ngày giao',
    jumpToDate: 'Đi tới ngày',
    clearDate: 'Xem gần đây',
    tomorrow: 'Ngày mai',
    overdue: 'Trễ hạn giao',
    noOdoo: 'Chưa có Odoo',
    latePay: '⚠ Trễ thanh toán',
    walkIn: 'Khách lẻ',
    paidFull: '✓ Đã thanh toán',
    unpaidFull: 'Chưa thanh toán',
    labDelivered: '✓ Lab đã giao',
    labNot: 'Lab chưa giao',
    shopDelivered: '✓ Shop đã giao',
    shopNot: 'Shop chưa giao',
    today: 'Hôm nay',
    thisMonth: 'Tháng này',
    merchLabel: 'Hàng hóa',
    grandLabel: 'Tổng cộng (kèm phí)',
    orders: 'đơn',
    last14: 'Doanh thu 14 ngày qua',
    trendAria: 'Xu hướng doanh thu 14 ngày',
    byShop: 'CA theo shop',
    byCat: 'CA theo danh mục sản phẩm',
    byChannel: 'CA theo kênh bán hàng',
    noData: 'Chưa có dữ liệu.',
    channelAdd: 'Thêm kênh mới...',
    priceLabel: 'Giá bán (₫)',
    listPrice: 'Giá niêm yết',
    lineNote: 'Ghi chú cho sản phẩm này...',
    payProof: 'Ảnh chuyển khoản',
    payProofDrop: '📎 Kéo thả hoặc chọn ảnh chuyển khoản',
    uploading: 'Đang tải ảnh...',
    sourceLabel: 'Nguồn hàng',
    srcLab: '🏭 Đặt lab (tạo Odoo)',
    srcStock: '🏪 Kho shop (không Odoo)',
    srcLabHint: 'Lab sản xuất → giao shop → shop giao khách. Tạo đơn Odoo + thẻ sản xuất.',
    srcStockHint: 'Hàng đã có sẵn tại shop (nhận từ REP). KHÔNG tạo Odoo, KHÔNG sản xuất — shop lấy từ kho giao khách và vẫn bấm bán tại quầy như bình thường.',
    submitStock: 'Lưu đơn bán từ kho',
    savingStock: 'Đang lưu...',
    okStock: 'Đã lưu đơn bán từ kho — shop đã được thông báo',
    stockBadge: '🏪 Kho shop',
    importBadge: '📥 Nhập từ lịch sử',
    needsItemsBadge: '✏️ Cần bổ sung chi tiết',
    reconstructTitle: 'Bổ sung chi tiết đơn hàng cũ',
    reconstructHint: 'Văn bản gốc: ',
    reconstructSearchPh: 'Tìm sản phẩm để thay thế...',
    reconstructSave: 'Lưu chi tiết',
    reconstructCancel: 'Huỷ',
    reconstructSaving: 'Đang lưu...',
    reconstructEmpty: 'Chưa chọn sản phẩm nào',
    reconstructAddMore: 'Có thể thêm nhiều sản phẩm — tìm và chọn lần lượt từng món.',
    reconstructOriginalTotal: 'Tổng tiền gốc: ',
    reconstructMismatch: 'Tổng hiện tại khác tổng gốc — kiểm tra lại đơn giá trước khi lưu',
    saleDate: 'Ngày bán',
    period: 'Khoảng thời gian',
    p14: '14 ngày', p30: '30 ngày', p90: '90 ngày', p365: '12 tháng',
    rangeTotal: 'Doanh thu trong kỳ (hàng hóa)',
    rangeGrandTotal: 'kèm phí',
    revenueTrend: 'Doanh thu theo thời gian',
    perWeek: 'theo tuần', perMonth: 'theo tháng', perDay: 'theo ngày',
    feesLabel: 'Phụ phí thêm',
    manageFees: 'Quản lý',
    feesRow: 'Phụ phí',
    feeBadge: 'Phụ phí',
    addFeeType: 'Loại khác',
    manageFeesTitle: 'Quản lý phụ phí',
    manageFeesHint: 'Danh sách dùng chung cho mọi người có quyền vào Đặt hàng Online — thêm, đổi giá hoặc xoá bất cứ lúc nào.',
    newFeeNamePh: 'Tên phụ phí mới...',
    newFeePricePh: 'Giá',
    addBtn: 'Thêm',
    newCustomerBadge: 'Khách mới',
    returningCustomerBadge: 'Khách cũ',
    priorOrdersSuffix: 'đơn trước',
    returningManualTag: 'đã xác nhận',
    markReturning: 'Đánh dấu là khách cũ',
    clearReturningOverride: 'Bỏ đánh dấu',
    exportBtn: 'Xuất Excel',
    exportFrom: 'Từ ngày',
    exportTo: 'Đến ngày',
    tabCustomers: 'Khách hàng',
    titleCustomers: 'Cơ sở dữ liệu khách hàng',
    custSearchPh: 'Tìm theo tên hoặc số điện thoại...',
    custPillNew: 'Mới',
    custPillReturning: 'Khách cũ',
    custCountSuffix: 'khách hàng',
    custNoResults: 'Không có khách hàng nào.',
    custPhoneLabel: 'Số điện thoại',
    custLastAddress: 'Địa chỉ gần nhất',
    custTotalOrdersLabel: 'Tổng số đơn',
    custOrderHistory: 'Lịch sử đơn hàng',
    custOriginOnline: '🛍️ Online',
    custPriceUnknown: 'Chưa ghi nhận giá',
    custCancelled: 'Đã huỷ',
    custBackAria: 'Quay lại',
  },
  en: {
    titleOrder: 'Online orders',
    titleTrack: 'Order tracking',
    titleStats: 'Revenue stats',
    tabOrder: 'Order',
    tabTrack: 'Track',
    tabStats: 'Stats',
    items: 'items',
    bell: 'Notifications',
    logout: 'Log out',
    logoutConfirm: 'Log out of this account?',
    channelLabel: 'Sales channel',
    channelHint: 'Where the customer came from — for reporting only; it does not decide which shop handles the order.',
    shopLabel: 'Shop handling the order (Odoo document)',
    deliveryModeLabel: 'Who delivers to the customer',
    dmShop: '🏪 Via the shop',
    dmDirect: '🚚 Lab delivers direct',
    dmShopHint: 'The lab delivers to the shop, and the shop hands it to / delivers it to the customer (current default).',
    dmDirectHint: "The lab delivers straight to the customer's address, bypassing the shop.",
    addProduct: 'Add products',
    searchPh: 'Search a product by name...',
    unitPrice: 'Unit price (₫)',
    cakeMsg: 'Message on the cake (e.g. Happy Birthday Linh)',
    designNotes: 'Cake design notes...',
    designPhoto: 'Different design photo',
    designPhotoHint: 'Original design shown above. Add a reference photo only if the customer wants a DIFFERENT design.',
    customerInfo: 'Customer',
    custName: 'Customer name',
    custPhone: 'Phone number',
    address: 'Delivery address',
    extraNotes: 'Additional notes...',
    payment: 'Payment',
    deliveryFee: 'Delivery fee',
    total: 'Total',
    paid: '✓ Paid',
    unpaid: 'Unpaid',
    partial: 'Deposit',
    depositAmount: 'Deposit amount (₫)',
    creating: 'Creating order...',
    submit: 'Create order & send to Odoo',
    errChannel: 'Pick or type a sales channel',
    errEmpty: 'Cart is empty',
    okOdoo: 'Odoo order created: ',
    okSaved: 'Order saved',
    fAll: 'All',
    fUndelivered: 'Not delivered',
    fLate: '⚠ Overdue',
    noOrders: 'No orders yet.',
    deliveryDateGroup: 'Delivery',
    noDeliveryDate: 'No delivery date',
    jumpToDate: 'Jump to date',
    clearDate: 'Show recent',
    tomorrow: 'Tomorrow',
    overdue: 'Overdue',
    noOdoo: 'No Odoo doc',
    latePay: '⚠ Late payment',
    walkIn: 'Walk-in customer',
    paidFull: '✓ Paid',
    unpaidFull: 'Unpaid',
    labDelivered: '✓ Lab delivered',
    labNot: 'Lab not delivered',
    shopDelivered: '✓ Shop delivered',
    shopNot: 'Shop not delivered',
    today: 'Today',
    thisMonth: 'This month',
    merchLabel: 'Merchandise',
    grandLabel: 'Total (with fees)',
    orders: 'orders',
    last14: 'Revenue, last 14 days',
    trendAria: '14-day revenue trend',
    byShop: 'Revenue by shop',
    byCat: 'Revenue by product category',
    byChannel: 'Revenue by sales channel',
    noData: 'No data yet.',
    channelAdd: 'Add a new channel...',
    priceLabel: 'Price (₫)',
    listPrice: 'List price',
    lineNote: 'Note for this item...',
    payProof: 'Payment screenshot',
    payProofDrop: '📎 Drop or pick the payment screenshot',
    uploading: 'Uploading...',
    sourceLabel: 'Stock source',
    srcLab: '🏭 Lab order (creates Odoo)',
    srcStock: '🏪 Shop stock (no Odoo)',
    srcLabHint: 'Lab produces → delivers to the shop → shop delivers the customer. Creates the Odoo document + production card.',
    srcStockHint: 'Product already on the shop shelf (from the REP). NO Odoo document, NO production — the shop hands it over from its stock and still rings it in the POS as usual.',
    submitStock: 'Save shop-stock sale',
    savingStock: 'Saving...',
    okStock: 'Shop-stock sale saved — the shop has been notified',
    stockBadge: '🏪 Shop stock',
    importBadge: '📥 Imported (history)',
    needsItemsBadge: '✏️ Detail needed',
    reconstructTitle: 'Fill in this historical order',
    reconstructHint: 'Original text: ',
    reconstructSearchPh: 'Search a product to replace it...',
    reconstructSave: 'Save detail',
    reconstructCancel: 'Cancel',
    reconstructSaving: 'Saving...',
    reconstructEmpty: 'No product picked yet',
    reconstructAddMore: 'You can add more than one product — search and pick each one in turn.',
    reconstructOriginalTotal: 'Original total: ',
    reconstructMismatch: "Current total doesn't match the original — double-check the price before saving",
    saleDate: 'Sale date',
    period: 'Period',
    p14: '14 days', p30: '30 days', p90: '90 days', p365: '12 months',
    rangeTotal: 'Revenue in period (merchandise)',
    rangeGrandTotal: 'with fees',
    revenueTrend: 'Revenue over time',
    perWeek: 'weekly', perMonth: 'monthly', perDay: 'daily',
    feesLabel: 'Extra fees',
    manageFees: 'Manage',
    feesRow: 'Extra fees',
    feeBadge: 'Fee',
    addFeeType: 'Other',
    manageFeesTitle: 'Manage extra fees',
    manageFeesHint: 'Shared with everyone who has access to online orders — add, reprice, or remove anytime.',
    newFeeNamePh: 'New fee name...',
    newFeePricePh: 'Price',
    addBtn: 'Add',
    newCustomerBadge: 'New customer',
    returningCustomerBadge: 'Returning customer',
    priorOrdersSuffix: 'prior orders',
    returningManualTag: 'confirmed',
    markReturning: 'Mark as returning',
    clearReturningOverride: 'Clear',
    exportBtn: 'Export Excel',
    exportFrom: 'From',
    exportTo: 'To',
    tabCustomers: 'Customers',
    titleCustomers: 'Customer database',
    custSearchPh: 'Search by name or phone number...',
    custPillNew: 'New',
    custPillReturning: 'Returning',
    custCountSuffix: 'customers',
    custNoResults: 'No customers yet.',
    custPhoneLabel: 'Phone',
    custLastAddress: 'Last known address',
    custTotalOrdersLabel: 'Total orders',
    custOrderHistory: 'Order history',
    custOriginOnline: '🛍️ Online',
    custPriceUnknown: 'Price not recorded',
    custCancelled: 'Cancelled',
    custBackAria: 'Back',
  },
} as const;
export type LKey = keyof typeof L.vi;
export function useL() {
  const { lang, setLang } = useI18n();
  const d = (lang === 'en' ? L.en : L.vi) as Record<LKey, string>;
  return { tr: (k: LKey) => d[k], lang, setLang };
}
